### ISSUE TITLE
HATS iOS 2.0 / HATS Web 5.0 Deployment Checklist

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#523]
- [x] Right at 9:00 AM, turn bridge feature type back on
- [x] Take web app and iOS services offline starting at 9:00 AM
- [x] Update snapshot tables and verify 3 new feature types are in them
- [x] Take GIS 1.5 map service offline (Prod)
- [x] Have DBA backup CA database
- [x] Run schema upgrade scripts
- [x] Run stored proc upgrade scripts on prod DB
- [x] Give @ReedHunter-Wsdot all clear to load data into 2.0 Prod Map Service
- [x] Deploy HATS Web 5.0 (keep offline)
- [x] Josh: Verify Commitment Tracking System still works after schema updates and column removal.
- [x] Update iOS project info.plist to point to new 2.0 Prod Map Service
- [x] Update feature geodatabase generator to point to 2.0 Prod Map Service
- [x] Version bump on iOS project to just 2.0
- [x] Generate RC build to be ready for testing once Map Service loaded with data.
- [x] Run Local DB generator to produce offline copy for latest schema (31), then place it on app server so it can run on schedule
- [x] Map Service loaded with data, run Feature Geodatabase generator to place features geodatabase in download spot, then place it on app server so it can run on schedule
- [x] Deploy 2.0 RC at /rc 
- [x] Bring HATS Web 5.0 back online 
- [x] Quick developer testing of 2.0 RC (Add, Edit, Insert feature and add record of each type)
- [x] @joeschmit's team testing of 2.0 RC
- [x] On signoff, move from /rc to prod deployment url and ask Field Services to push to all users

@ReedHunter-Wsdot feel free to add steps to this. More high level tasks. Just don't want to forget anything. This one we need to get done as quick as possible so we can push out to users. We have users heading out to do the MAP Survey's starting Tuesday morning.

**Comment by ReedHunter-Wsdot** [comment]
Before Monday, 
- [x] Prep models for loading the 1st and 2nd file geodatabases

After @jhudsonWA gives me all clear to load data from snapshots ...
- [x] Reed: load current prod spatial data from snapshots to 1st intermediate file gdb
- [x] Reed: project data from 1st intermediate file gdb to Web Mercator in 2nd file gdb
- [x] Reed: one by one load projected feature tables from 2nd file gdb to prod enterprise gdb
- [x] Update map feature service with last minute layer changes (no culvert ends, include Snow and Ice Materials Storage layer)
- [x] Reed: verify map feature service has the data, then notify @jhudsonWA

**Comment by jhudsonWA** [comment]
Shipped!
